import { GetList } from './list';
import { RenameFile } from './rename';
import { MoveFiles } from './move';
import { CopyFiles } from './copy';
import { RemoveFiles } from './remove';
import { EditFile } from './edit';
import { GetFileContent } from './getContent';
import { GetSingle } from './getSingle';
import { CreateFolder } from './createFolder';
import { ChangePermissions } from './changePermissions';
import { UploadFile } from './uploadFile';
import { ChangePermissionsObject } from './changePermissionsObject';
export declare const commands: {
    GetList: typeof GetList;
    RenameFile: typeof RenameFile;
    MoveFiles: typeof MoveFiles;
    CopyFiles: typeof CopyFiles;
    RemoveFiles: typeof RemoveFiles;
    EditFile: typeof EditFile;
    GetFileContent: typeof GetFileContent;
    GetSingle: typeof GetSingle;
    CreateFolder: typeof CreateFolder;
    ChangePermissions: typeof ChangePermissions;
    ChangePermissionsObject: typeof ChangePermissionsObject;
    UploadFile: typeof UploadFile;
};
